# -*- coding: utf-8 -*-
"""layer_blocks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wbE46gcSkyyPBW-z1fYUCnA7herHuPf9
"""

# IMPORTING python libraries
import numpy as np
import imageio
from tqdm import tqdm
import cv2
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import tensorflow_addons as tfa
from utility import utils

class blocks:
  def __init__(self):
      self.SpFilters = 32
       
  # Convolution blocks ----------Conv,Norm,Act,Pool,Dropout-----------------------------------------
  def Conv_block(self,x,filters,s = 3, act= 'leaky',scale = 'None',dropout = False,norm = 'batch'):

      x = utils.ConvLayer(x,filters,size=s)
      x = utils.Normalization(x,type = norm)
      x = utils.activation(x,act =act)

      if scale is 'up':
        x = utils.DownPool(x)
      elif scale is 'down':
        x = utils.UpPool(x)
      else:
        x = x
      
      if dropout is True:
        x = layers.Dropout(0.2)(x)

      return x  

  # Residual blocks---------------------------------------------------------------------------------------
  def res_block(self,x,filters,act = 'relu',no_of_layers = 2):
      current_filters = tf.shape(x)[-1]

      for i in range(no_of_layers):
        x = utils.Normalization(x,type = 'batch')
        x = utils.activation(x,act = act)
        x = utils.ConvLayer(t,filters,size=s)

      
      if current_filters is not filters:
        z = utils.ConvLayer(t,filters,size=1)

      return x + z

    # Spatially Adaptive De Normalization Layer------------------------------------------------------------
    def SPADE(self,x,pb,filters,s = 3, norm = 'parafree'):
        
        x = utils.Normalization(x,type = norm)
        
        y = utils.ConvLayer(pb,self.SpFilters,size = s)
        y = utils.activation(y,act = 'relu')

        gamma = utils.ConvLayer(x,filters,size = s)
        beta = utils.ConvLayer(x,filters,size = s)
                
        out = x*(1 + gamma) + beta        
        return out
    
    # SPADE residual blocks ------------------------------------------------------------------------------
    def SPADE_ResBlock(self,x,pb,filters,s = 3, no_of_spade = 2):
        current_filters = tf.shape(x)[-1]
        x = t

        for i in range(no_of_spade):
          x = self.SPADE(x,pb,current_filters)
          x = utils.activation(x,act = 'leaky')
          x = utils.ConvLayer(x,filters,size =s)
        
        if current_filters is not filters:
          z = self.SPADE(t,pb,filters)
          z = utils.activation(t,act = 'leaky')
          z = utils.ConvLayer(t,filters,size =s)
        else:
          z = t
        
        return x + z